### ISSUE TITLE
Tools Bar does not exist

### ISSUE THREAD

**Issue by GD-NTB** [atomic-software/TISFAT-Zero#83]
So I searched through the internet and found that everyone else had a toolbar in TISFAT except me. Also, when I load the program, it comes up with this error:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TISFAT.AutoUpdateDialog.CheckForUpdates(Boolean user) in C:\Users\diges\Desktop\TISFAT-Zero-master\TISFAT\UI\Dialogs\AutoUpdateDialog.cs:line 56
   at TISFAT.MainForm.MainForm_Load(Object sender, EventArgs e) in C:\Users\diges\Desktop\TISFAT-Zero-master\TISFAT\UI\MainForm.cs:line 91
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2671.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TISFAT
    Assembly Version: 1.4.6.0
    Win32 Version: 1.4.6.0
    CodeBase: file:///C:/Users/diges/Desktop/TISFAT-Zero-master/TISFAT/bin/x86/Debug/TISFAT.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------

**Comment by evsl** [comment]
Hey Digestivbiscuit,

I'm aware of the exception; This is due to github since changing something about their API. Internally the update checker tries to fetch some info from here, but it's not supplying a proper User Agent, which was fine 3 years ago, but not so much anymore.

This probably won't be fixed for TISFAT Zero, however, because I've been working on a much more up to date iteration of tisfat as of late. If anything, TISFAT will continue through this new project. I haven't publicized development of it yet since I'm quite busy with work.

I've been debating on whether or not I want to fix the latent issues with TISFAT Zero in the meantime, but that's a large undertaking in itself; and working with code that I wrote many years ago isn't the most fun. Interesting to see the interest, though; I'd assumed most people forgot about this software by now.
